# Generated by Django 5.2.8 on 2025-11-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='user_id',
            field=models.CharField(default='', max_length=250),
        ),
    ]
