# Generated by Django 5.2.8 on 2025-11-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0004_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='status',
            field=models.CharField(default='Unpaid', max_length=250),
        ),
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(default='Paid', max_length=250),
        ),
    ]
